/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.1/userguide/multi_project_builds.html
 */

rootProject.name = "okapi-server"
// 统一插件管理
pluginManagement {
    val kotlinVersion = "1.7.20"
    plugins {
        kotlin("jvm") version kotlinVersion apply false
        kotlin("plugin.spring") version kotlinVersion apply false
        kotlin("allopen") version kotlinVersion
        kotlin("plugin.jpa") version kotlinVersion apply false
        id("org.springframework.boot") version "2.5.5" apply false
        id("io.spring.dependency-management") version "1.0.11.RELEASE" apply false
    }
    repositories {
        mavenLocal()
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

// 统一依赖管理
dependencyResolutionManagement {
    @Suppress("UnstableApiUsage")
    repositories {
        mavenLocal()
        mavenCentral()
        google()
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/open-okapi/data-driven-okhttp")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

include("server")
